### ISSUE TITLE
Asia/Tehran format should not use 'J'

### ISSUE THREAD

**Issue by Diramu** [nayarsystems/posix_tz_db#3]
Currently Tehran has entry:
"Asia/Tehran","<+0330>-3:30<+0430>,J80/0,J264/0"
I believe it should be 
"Asia/Tehran","<+0330>-3:30<+0430>,80/0,264/0"

From http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
 
```
Jn
This specifies the Julian day, with n between 1 and 365. February 29 is never counted, even in leap years.

n
This specifies the Julian day, with n between 0 and 365. February 29 is counted in leap years.

```

From https://en.wikipedia.org/wiki/Iran_Standard_Time:
```
The Iranian DST starts on March 22 and ends on September 22 each year with the exception of leapyears in which the DST starts and ends one day prior.

Year | DST Start Date and Time | DST End Date and Time
-- | -- | --
2014 | Sat, Mar 22, 0:00 AM | Mon, Sep 22, 0:00 AM
2015 | Sun, Mar 22, 0:00 AM | Tue, Sep 22, 0:00 AM
2016 | Mon, Mar 21, 0:00 AM | Wed, Sep 21, 0:00 AM
2017 | Wed, Mar 22, 0:00 AM | Fri, Sep 22, 0:00 AM
2018 | Thu, Mar 22, 0:00 AM | Sat, Sep 22, 0:00 AM

```
This mean Feb 29. should be counted.  No 'J'.
I'm calculating Mar 21, not Mar with the current format, because the count starts a 1.  Counting from 0,  will result in Mar 22 (and Mar 21 on a leap year)

**Comment by jaracil** [comment]
The POSIX TZ strings are obtained from /usr/share/zoneinfo directory in Arch Linux system.
We can't patch individual strings from .json and .csv files, because they are autogenerated every time there is a new time-zone update.

**Comment by Docteh** [comment]
@Diramu as an outside observer I'm noticing that the timezone for Asia/Tehran is now `<+0330>-3:30<+0430>,J79/24,J263/24`

Personally I'm using Ubuntu, which has Debian as upstream, https://packages.debian.org/sid/tzdata
https://www.iana.org/time-zones

snippet from the asia file
```
Rule	Iran	2000	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2000	only	-	Sep	20	24:00	0	-
Rule	Iran	2001	2003	-	Mar	21	24:00	1:00	-
Rule	Iran	2001	2003	-	Sep	21	24:00	0	-
Rule	Iran	2004	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2004	only	-	Sep	20	24:00	0	-
Rule	Iran	2005	only	-	Mar	21	24:00	1:00	-
Rule	Iran	2005	only	-	Sep	21	24:00	0	-
Rule	Iran	2008	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2008	only	-	Sep	20	24:00	0	-
Rule	Iran	2009	2011	-	Mar	21	24:00	1:00	-
Rule	Iran	2009	2011	-	Sep	21	24:00	0	-
Rule	Iran	2012	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2012	only	-	Sep	20	24:00	0	-
Rule	Iran	2013	2015	-	Mar	21	24:00	1:00	-
Rule	Iran	2013	2015	-	Sep	21	24:00	0	-
Rule	Iran	2016	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2016	only	-	Sep	20	24:00	0	-
Rule	Iran	2017	2019	-	Mar	21	24:00	1:00	-
Rule	Iran	2017	2019	-	Sep	21	24:00	0	-
Rule	Iran	2020	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2020	only	-	Sep	20	24:00	0	-
Rule	Iran	2021	2023	-	Mar	21	24:00	1:00	-
Rule	Iran	2021	2023	-	Sep	21	24:00	0	-
Rule	Iran	2024	only	-	Mar	20	24:00	1:00	-
Rule	Iran	2024	only	-	Sep	20	24:00	0	-
```

They appear to be hard coding every leap year. Looks like the older POSIX TZ variables are better at handling leap years than the more modern IANA  data.
