### ISSUE TITLE
Issue with recent zoneinfo updates

### ISSUE THREAD

**Issue by d-a-v** [nayarsystems/posix_tz_db#4]
Hello,
Africa/ Casablanca and El_Aaiun both return an empty string.
It seems zoneinfo format has changed for these two cities.

**Comment by soyangel** [comment]
As you can see in the Python script `gen-tz.py` we extract all strings from /usr/share/zoneinfo. So it seems like Casablanca and El_Aaiun have empty strings.

We prefer not to set these values manually and trust what is on these files.

**Comment by d-a-v** [comment]
It will hopefully be fixed in next release of these files per [upstream fix](https://mm.icann.org/pipermail/tz/2019-May/027962.html).

**Comment by d-a-v** [comment]
FWIW FIY upstream has been updated and the empty string issue is now fixed.

**Comment by jaracil** [comment]
Updated!
