### ISSUE TITLE
Copyright details are missing in the LICENSE

### ISSUE THREAD

**Issue by shahpiyushv** [nayarsystems/posix_tz_db#6]
The [LICENSE](https://github.com/nayarsystems/posix_tz_db/blob/master/LICENSE) does not have name and year. Can you add those?

**Comment by jdlambert** [comment]
In responding to the above user's request on [my fork](https://github.com/jdlambert/micro_tz_db) of this repo, I'll be removing the name- and year- less copyright line from the license, as it doesn't properly reflect your copyright.

I'll watch for you to get around to updating it here, when that happens I'll add it back with your info!
